---
Name: elemental
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'dnadesign/silverstripe-elemental:client/dist/styles/bundle.css'

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalContentControllerExtension
  url_handlers:
    'element/$ID!': 'handleElement'

SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - 'DNADesign\Elemental\Extensions\GridFieldDetailFormItemRequestExtension'

Symbiote\GridFieldExtensions\GridFieldAddNewMultiClassHandler:
  extensions:
    - DNADesign\Elemental\Extensions\GridFieldAddNewMultiClassHandlerExtension
