---
Name: elemental
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalLeftAndMainExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalContentControllerExtension
  url_handlers:
    'element/$ID!': 'handleElement'

SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - 'DNADesign\Elemental\Extensions\GridFieldDetailFormItemRequestExtension'

Symbiote\GridFieldExtensions\GridFieldAddNewMultiClassHandler:
  extensions:
    - DNADesign\Elemental\Extensions\GridFieldAddNewMultiClassHandlerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\CMS\Controllers\CMSSiteTreeFilter_Search:
    class: DNADesign\Elemental\Controllers\ElementSiteTreeFilterSearch
